/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PosIndexRouteImport } from './routes/pos.index'
import { Route as SuperAdminUsersRouteImport } from './routes/super-admin.users'
import { Route as SuperAdminStoresRouteImport } from './routes/super-admin.stores'
import { Route as SuperAdminSettingsRouteImport } from './routes/super-admin.settings'
import { Route as SuperAdminOrdersRouteImport } from './routes/super-admin.orders'
import { Route as SuperAdminDashboardRouteImport } from './routes/super-admin.dashboard'
import { Route as SuperAdminAnalyticsRouteImport } from './routes/super-admin.analytics'
import { Route as StoreProductsRouteImport } from './routes/store.products'
import { Route as StoreEmployeesRouteImport } from './routes/store.employees'
import { Route as StoreDashboardRouteImport } from './routes/store.dashboard'
import { Route as StoreCategoriesRouteImport } from './routes/store.categories'
import { Route as StoreBranchesRouteImport } from './routes/store.branches'
import { Route as PosShiftRouteImport } from './routes/pos.shift'
import { Route as PosRefundsRouteImport } from './routes/pos.refunds'
import { Route as CustomerPortalRouteImport } from './routes/customer.portal'
import { Route as CustomerOrdersRouteImport } from './routes/customer.orders'
import { Route as BranchOrdersRouteImport } from './routes/branch.orders'
import { Route as BranchInventoryRouteImport } from './routes/branch.inventory'
import { Route as BranchDashboardRouteImport } from './routes/branch.dashboard'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PosIndexRoute = PosIndexRouteImport.update({
  id: '/pos/',
  path: '/pos/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminUsersRoute = SuperAdminUsersRouteImport.update({
  id: '/super-admin/users',
  path: '/super-admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminStoresRoute = SuperAdminStoresRouteImport.update({
  id: '/super-admin/stores',
  path: '/super-admin/stores',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminSettingsRoute = SuperAdminSettingsRouteImport.update({
  id: '/super-admin/settings',
  path: '/super-admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminOrdersRoute = SuperAdminOrdersRouteImport.update({
  id: '/super-admin/orders',
  path: '/super-admin/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminDashboardRoute = SuperAdminDashboardRouteImport.update({
  id: '/super-admin/dashboard',
  path: '/super-admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminAnalyticsRoute = SuperAdminAnalyticsRouteImport.update({
  id: '/super-admin/analytics',
  path: '/super-admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreProductsRoute = StoreProductsRouteImport.update({
  id: '/store/products',
  path: '/store/products',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreEmployeesRoute = StoreEmployeesRouteImport.update({
  id: '/store/employees',
  path: '/store/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreDashboardRoute = StoreDashboardRouteImport.update({
  id: '/store/dashboard',
  path: '/store/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreCategoriesRoute = StoreCategoriesRouteImport.update({
  id: '/store/categories',
  path: '/store/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreBranchesRoute = StoreBranchesRouteImport.update({
  id: '/store/branches',
  path: '/store/branches',
  getParentRoute: () => rootRouteImport,
} as any)
const PosShiftRoute = PosShiftRouteImport.update({
  id: '/pos/shift',
  path: '/pos/shift',
  getParentRoute: () => rootRouteImport,
} as any)
const PosRefundsRoute = PosRefundsRouteImport.update({
  id: '/pos/refunds',
  path: '/pos/refunds',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerPortalRoute = CustomerPortalRouteImport.update({
  id: '/customer/portal',
  path: '/customer/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerOrdersRoute = CustomerOrdersRouteImport.update({
  id: '/customer/orders',
  path: '/customer/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchOrdersRoute = BranchOrdersRouteImport.update({
  id: '/branch/orders',
  path: '/branch/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchInventoryRoute = BranchInventoryRouteImport.update({
  id: '/branch/inventory',
  path: '/branch/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchDashboardRoute = BranchDashboardRouteImport.update({
  id: '/branch/dashboard',
  path: '/branch/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/branch/dashboard': typeof BranchDashboardRoute
  '/branch/inventory': typeof BranchInventoryRoute
  '/branch/orders': typeof BranchOrdersRoute
  '/customer/orders': typeof CustomerOrdersRoute
  '/customer/portal': typeof CustomerPortalRoute
  '/pos/refunds': typeof PosRefundsRoute
  '/pos/shift': typeof PosShiftRoute
  '/store/branches': typeof StoreBranchesRoute
  '/store/categories': typeof StoreCategoriesRoute
  '/store/dashboard': typeof StoreDashboardRoute
  '/store/employees': typeof StoreEmployeesRoute
  '/store/products': typeof StoreProductsRoute
  '/super-admin/analytics': typeof SuperAdminAnalyticsRoute
  '/super-admin/dashboard': typeof SuperAdminDashboardRoute
  '/super-admin/orders': typeof SuperAdminOrdersRoute
  '/super-admin/settings': typeof SuperAdminSettingsRoute
  '/super-admin/stores': typeof SuperAdminStoresRoute
  '/super-admin/users': typeof SuperAdminUsersRoute
  '/pos/': typeof PosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/branch/dashboard': typeof BranchDashboardRoute
  '/branch/inventory': typeof BranchInventoryRoute
  '/branch/orders': typeof BranchOrdersRoute
  '/customer/orders': typeof CustomerOrdersRoute
  '/customer/portal': typeof CustomerPortalRoute
  '/pos/refunds': typeof PosRefundsRoute
  '/pos/shift': typeof PosShiftRoute
  '/store/branches': typeof StoreBranchesRoute
  '/store/categories': typeof StoreCategoriesRoute
  '/store/dashboard': typeof StoreDashboardRoute
  '/store/employees': typeof StoreEmployeesRoute
  '/store/products': typeof StoreProductsRoute
  '/super-admin/analytics': typeof SuperAdminAnalyticsRoute
  '/super-admin/dashboard': typeof SuperAdminDashboardRoute
  '/super-admin/orders': typeof SuperAdminOrdersRoute
  '/super-admin/settings': typeof SuperAdminSettingsRoute
  '/super-admin/stores': typeof SuperAdminStoresRoute
  '/super-admin/users': typeof SuperAdminUsersRoute
  '/pos': typeof PosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/branch/dashboard': typeof BranchDashboardRoute
  '/branch/inventory': typeof BranchInventoryRoute
  '/branch/orders': typeof BranchOrdersRoute
  '/customer/orders': typeof CustomerOrdersRoute
  '/customer/portal': typeof CustomerPortalRoute
  '/pos/refunds': typeof PosRefundsRoute
  '/pos/shift': typeof PosShiftRoute
  '/store/branches': typeof StoreBranchesRoute
  '/store/categories': typeof StoreCategoriesRoute
  '/store/dashboard': typeof StoreDashboardRoute
  '/store/employees': typeof StoreEmployeesRoute
  '/store/products': typeof StoreProductsRoute
  '/super-admin/analytics': typeof SuperAdminAnalyticsRoute
  '/super-admin/dashboard': typeof SuperAdminDashboardRoute
  '/super-admin/orders': typeof SuperAdminOrdersRoute
  '/super-admin/settings': typeof SuperAdminSettingsRoute
  '/super-admin/stores': typeof SuperAdminStoresRoute
  '/super-admin/users': typeof SuperAdminUsersRoute
  '/pos/': typeof PosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/branch/dashboard'
    | '/branch/inventory'
    | '/branch/orders'
    | '/customer/orders'
    | '/customer/portal'
    | '/pos/refunds'
    | '/pos/shift'
    | '/store/branches'
    | '/store/categories'
    | '/store/dashboard'
    | '/store/employees'
    | '/store/products'
    | '/super-admin/analytics'
    | '/super-admin/dashboard'
    | '/super-admin/orders'
    | '/super-admin/settings'
    | '/super-admin/stores'
    | '/super-admin/users'
    | '/pos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/branch/dashboard'
    | '/branch/inventory'
    | '/branch/orders'
    | '/customer/orders'
    | '/customer/portal'
    | '/pos/refunds'
    | '/pos/shift'
    | '/store/branches'
    | '/store/categories'
    | '/store/dashboard'
    | '/store/employees'
    | '/store/products'
    | '/super-admin/analytics'
    | '/super-admin/dashboard'
    | '/super-admin/orders'
    | '/super-admin/settings'
    | '/super-admin/stores'
    | '/super-admin/users'
    | '/pos'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/signup'
    | '/branch/dashboard'
    | '/branch/inventory'
    | '/branch/orders'
    | '/customer/orders'
    | '/customer/portal'
    | '/pos/refunds'
    | '/pos/shift'
    | '/store/branches'
    | '/store/categories'
    | '/store/dashboard'
    | '/store/employees'
    | '/store/products'
    | '/super-admin/analytics'
    | '/super-admin/dashboard'
    | '/super-admin/orders'
    | '/super-admin/settings'
    | '/super-admin/stores'
    | '/super-admin/users'
    | '/pos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  BranchDashboardRoute: typeof BranchDashboardRoute
  BranchInventoryRoute: typeof BranchInventoryRoute
  BranchOrdersRoute: typeof BranchOrdersRoute
  CustomerOrdersRoute: typeof CustomerOrdersRoute
  CustomerPortalRoute: typeof CustomerPortalRoute
  PosRefundsRoute: typeof PosRefundsRoute
  PosShiftRoute: typeof PosShiftRoute
  StoreBranchesRoute: typeof StoreBranchesRoute
  StoreCategoriesRoute: typeof StoreCategoriesRoute
  StoreDashboardRoute: typeof StoreDashboardRoute
  StoreEmployeesRoute: typeof StoreEmployeesRoute
  StoreProductsRoute: typeof StoreProductsRoute
  SuperAdminAnalyticsRoute: typeof SuperAdminAnalyticsRoute
  SuperAdminDashboardRoute: typeof SuperAdminDashboardRoute
  SuperAdminOrdersRoute: typeof SuperAdminOrdersRoute
  SuperAdminSettingsRoute: typeof SuperAdminSettingsRoute
  SuperAdminStoresRoute: typeof SuperAdminStoresRoute
  SuperAdminUsersRoute: typeof SuperAdminUsersRoute
  PosIndexRoute: typeof PosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos/': {
      id: '/pos/'
      path: '/pos'
      fullPath: '/pos/'
      preLoaderRoute: typeof PosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/users': {
      id: '/super-admin/users'
      path: '/super-admin/users'
      fullPath: '/super-admin/users'
      preLoaderRoute: typeof SuperAdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/stores': {
      id: '/super-admin/stores'
      path: '/super-admin/stores'
      fullPath: '/super-admin/stores'
      preLoaderRoute: typeof SuperAdminStoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/settings': {
      id: '/super-admin/settings'
      path: '/super-admin/settings'
      fullPath: '/super-admin/settings'
      preLoaderRoute: typeof SuperAdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/orders': {
      id: '/super-admin/orders'
      path: '/super-admin/orders'
      fullPath: '/super-admin/orders'
      preLoaderRoute: typeof SuperAdminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/dashboard': {
      id: '/super-admin/dashboard'
      path: '/super-admin/dashboard'
      fullPath: '/super-admin/dashboard'
      preLoaderRoute: typeof SuperAdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/analytics': {
      id: '/super-admin/analytics'
      path: '/super-admin/analytics'
      fullPath: '/super-admin/analytics'
      preLoaderRoute: typeof SuperAdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/products': {
      id: '/store/products'
      path: '/store/products'
      fullPath: '/store/products'
      preLoaderRoute: typeof StoreProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/employees': {
      id: '/store/employees'
      path: '/store/employees'
      fullPath: '/store/employees'
      preLoaderRoute: typeof StoreEmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/dashboard': {
      id: '/store/dashboard'
      path: '/store/dashboard'
      fullPath: '/store/dashboard'
      preLoaderRoute: typeof StoreDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/categories': {
      id: '/store/categories'
      path: '/store/categories'
      fullPath: '/store/categories'
      preLoaderRoute: typeof StoreCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/branches': {
      id: '/store/branches'
      path: '/store/branches'
      fullPath: '/store/branches'
      preLoaderRoute: typeof StoreBranchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos/shift': {
      id: '/pos/shift'
      path: '/pos/shift'
      fullPath: '/pos/shift'
      preLoaderRoute: typeof PosShiftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos/refunds': {
      id: '/pos/refunds'
      path: '/pos/refunds'
      fullPath: '/pos/refunds'
      preLoaderRoute: typeof PosRefundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/portal': {
      id: '/customer/portal'
      path: '/customer/portal'
      fullPath: '/customer/portal'
      preLoaderRoute: typeof CustomerPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/orders': {
      id: '/customer/orders'
      path: '/customer/orders'
      fullPath: '/customer/orders'
      preLoaderRoute: typeof CustomerOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branch/orders': {
      id: '/branch/orders'
      path: '/branch/orders'
      fullPath: '/branch/orders'
      preLoaderRoute: typeof BranchOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branch/inventory': {
      id: '/branch/inventory'
      path: '/branch/inventory'
      fullPath: '/branch/inventory'
      preLoaderRoute: typeof BranchInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branch/dashboard': {
      id: '/branch/dashboard'
      path: '/branch/dashboard'
      fullPath: '/branch/dashboard'
      preLoaderRoute: typeof BranchDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  BranchDashboardRoute: BranchDashboardRoute,
  BranchInventoryRoute: BranchInventoryRoute,
  BranchOrdersRoute: BranchOrdersRoute,
  CustomerOrdersRoute: CustomerOrdersRoute,
  CustomerPortalRoute: CustomerPortalRoute,
  PosRefundsRoute: PosRefundsRoute,
  PosShiftRoute: PosShiftRoute,
  StoreBranchesRoute: StoreBranchesRoute,
  StoreCategoriesRoute: StoreCategoriesRoute,
  StoreDashboardRoute: StoreDashboardRoute,
  StoreEmployeesRoute: StoreEmployeesRoute,
  StoreProductsRoute: StoreProductsRoute,
  SuperAdminAnalyticsRoute: SuperAdminAnalyticsRoute,
  SuperAdminDashboardRoute: SuperAdminDashboardRoute,
  SuperAdminOrdersRoute: SuperAdminOrdersRoute,
  SuperAdminSettingsRoute: SuperAdminSettingsRoute,
  SuperAdminStoresRoute: SuperAdminStoresRoute,
  SuperAdminUsersRoute: SuperAdminUsersRoute,
  PosIndexRoute: PosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
